/**
 * One-off script: looks up a real food photo per recipe via the Wikimedia
 * Commons search API (free, no API key/account required) and writes the
 * results to prisma/data/images.ts as a slug -> URL map.
 *
 * Run with: npx tsx scripts/fetch-recipe-images.ts
 *
 * This runs once at dev time, not at request time or seed time — seeding
 * stays deterministic and offline; this script is what refreshes the cache.
 */
import { RECIPES } from "../prisma/data/recipes";
import { writeFileSync, existsSync, readFileSync } from "fs";
import { join } from "path";

const OUT_PATH = join(__dirname, "..", "prisma", "data", "images.ts");

function loadExisting(): Record<string, string> {
  if (!existsSync(OUT_PATH)) return {};
  const content = readFileSync(OUT_PATH, "utf-8");
  const match = content.match(/RECIPE_IMAGES:.*?=\s*(\{[\s\S]*\});/);
  if (!match) return {};
  try {
    return JSON.parse(match[1]);
  } catch {
    return {};
  }
}

const BAD_TITLE_WORDS = [
  "logo", "map", "diagram", "flag", "chart", "icon", "restaurant",
  "menu", "chef ", "person", "portrait", "building", "sign",
];

type CommonsImage = {
  title: string;
  url: string;
  width: number;
  height: number;
};

async function searchCommons(query: string, attempt = 1): Promise<CommonsImage[]> {
  const url = new URL("https://commons.wikimedia.org/w/api.php");
  url.searchParams.set("action", "query");
  url.searchParams.set("format", "json");
  url.searchParams.set("generator", "search");
  url.searchParams.set("gsrsearch", `${query} food filetype:bitmap`);
  url.searchParams.set("gsrlimit", "6");
  url.searchParams.set("gsrnamespace", "6");
  url.searchParams.set("prop", "imageinfo");
  url.searchParams.set("iiprop", "url|size|mime");
  url.searchParams.set("iiurlwidth", "800");
  url.searchParams.set("origin", "*");

  const res = await fetch(url.toString(), {
    headers: { "User-Agent": "SkilletApp/1.0 (personal-project meal planner; recipe image lookup script)" },
  });

  if (res.status === 429 || res.status === 503) {
    if (attempt > 5) return [];
    const wait = attempt * 4000;
    console.log(`  (rate limited, waiting ${wait}ms, attempt ${attempt})`);
    await new Promise((r) => setTimeout(r, wait));
    return searchCommons(query, attempt + 1);
  }

  if (!res.ok) return [];
  const data = await res.json();
  const pages = data?.query?.pages;
  if (!pages) return [];

  return Object.values(pages)
    .map((p: any) => {
      const info = p.imageinfo?.[0];
      if (!info) return null;
      return {
        title: p.title as string,
        url: (info.thumburl ?? info.url) as string,
        width: info.thumbwidth ?? info.width,
        height: info.thumbheight ?? info.height,
      };
    })
    .filter((x): x is CommonsImage => !!x);
}

function pickBest(images: CommonsImage[]): string | null {
  const candidates = images.filter((img) => {
    const lower = img.title.toLowerCase();
    if (BAD_TITLE_WORDS.some((w) => lower.includes(w))) return false;
    if (img.width < 400) return false;
    const ratio = img.width / Math.max(1, img.height);
    if (ratio < 0.5 || ratio > 2.2) return false; // skip extreme aspect ratios
    return true;
  });
  return candidates[0]?.url ?? images[0]?.url ?? null;
}

async function main() {
  const results: Record<string, string> = loadExisting();
  let found = Object.keys(results).length;
  console.log(`Resuming with ${found} already cached.\n`);

  for (const recipe of RECIPES) {
    if (results[recipe.slug]) continue;
    const query = `${recipe.name}`;
    try {
      const images = await searchCommons(query);
      let picked = pickBest(images);

      if (!picked) {
        // Fallback: broaden to cuisine + main protein/dish type
        const fallbackImages = await searchCommons(`${recipe.cuisine} ${recipe.proteinType} dish`);
        picked = pickBest(fallbackImages);
      }

      if (picked) {
        results[recipe.slug] = picked;
        found++;
        console.log(`✓ ${recipe.slug}`);
      } else {
        console.log(`✗ ${recipe.slug} (no match)`);
      }
    } catch (err) {
      console.log(`✗ ${recipe.slug} (error: ${(err as Error).message})`);
    }
    writeResults(results);
    await new Promise((r) => setTimeout(r, 1500));
  }

  writeResults(results);
  console.log(`\nDone: ${Object.keys(results).length}/${RECIPES.length} recipes matched. Wrote prisma/data/images.ts`);
}

function writeResults(results: Record<string, string>) {
  const fileContent = `// Auto-generated by scripts/fetch-recipe-images.ts — do not hand-edit.
// Maps recipe slug -> a real food photo URL sourced from Wikimedia Commons
// (freely licensed, no API key required). Re-run the script to refresh
// (it resumes from what's already cached here).

export const RECIPE_IMAGES: Record<string, string> = ${JSON.stringify(results, null, 2)};
`;
  writeFileSync(OUT_PATH, fileContent);
}

main();
